# action.yml

name: minio-upload
description: "Action that lets you upload objects from a MinIO server"
inputs:
  url:
    description: "URL of the MinIO server"
    required: true
  access-key:
    description: "Access Key for the MinIO server"
    required: true
  secret-key:
    description: "Secret Key for the MinIO server"
    required: true
  local-path:
    description: 'Path of the local object'
    required: true
    default: './'
  remote-path:
    description: 'Path to remote object'
    required: true
  policy:
    description: 'Policy'
    required: false

runs:
  using: composite
  steps:
    - name: Check if mc is installed
      id: check-mc
      run: |
        if [[ -n "$(which mc)" ]]; then
          echo "exists=true" >> "$GITHUB_OUTPUT"
        else
          echo "exists=false" >> "$GITHUB_OUTPUT"
        fi
      shell: bash

    - name: Download latest mc SHA256
      id: mc-sha
      if: steps.check-mc.outputs.exists == 'false'
      run: |
        arch=$(dpkg --print-architecture | sed 's/armhf/arm/g')
        sha=$(wget -qO- \
          "https://dl.min.io/client/mc/release/linux-${arch}/mc.sha256sum" \
          | awk '{print $1}')
        echo "sha256=$sha" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Cache mc binary
      id: cache-mc
      if: steps.check-mc.outputs.exists == 'false'
      uses: actions/cache@v5
      with:
        path: /usr/local/bin/mc
        key: "mc-${{ steps.mc-sha.outputs.sha256 }}"

    - name: Setup mc
      working-directory: /usr/local/bin
      if: >-
        steps.check-mc.outputs.exists == 'false' &&
        steps.cache-mc.outputs.cache-hit != 'true'
      run: |
        arch=$(dpkg --print-architecture | sed 's/armhf/arm/g')
        sudo wget --progres=dot:binary \
          "https://dl.min.io/client/mc/release/linux-${arch}/mc"
        sudo chmod +x mc
      shell: bash

    - name: Setup s3 alias
      env:
        URL: ${{ inputs.url }}
        ACCESS_KEY: ${{ inputs.access-key }}
        SECRET_KEY: ${{ inputs.secret-key }}
      run: mc alias set s3 "$URL" "$ACCESS_KEY" "$SECRET_KEY"
      shell: bash

    - name: Upload objects
      env:
        LOCAL_PATH: ${{ inputs.local-path }}
        REMOTE_PATH: ${{ inputs.remote-path }}
      run: |
        echo "Will upload ${LOCAL_PATH} to ${REMOTE_PATH}"
        if [[ "${LOCAL_PATH#*'*'}" != "$LOCAL_PATH" ]]; then
          # Handle local_files with wildcards
          local_dir=$(dirname "$LOCAL_PATH")
          local_files=$(basename "$LOCAL_PATH")
          IFS=$'\n'
          for p in $(find "$local_dir" -maxdepth 1 -name "$local_files" |
            sort -u); do
              [[ "$p" != "$local_dir" ]] || continue
              mc cp -r "$p" "s3/${REMOTE_PATH}"
          done
          unset IFS
        else
          mc cp -r "$LOCAL_PATH" "s3/${REMOTE_PATH}"
        fi
      shell: bash

    - name: Set policy
      env:
        POLICY: ${{ inputs.policy }}
        REMOTE_PATH: ${{ inputs.remote-path }}
      run: |
        if [[ "$POLICY" == 1 ]]; then
          echo "Will make ${REMOTE_PATH} public"
          mc anonymous -r set download "s3/${REMOTE_PATH}"
        else
          echo "Will make ${REMOTE_PATH} private"
          mc anonymous -r set private "s3/${REMOTE_PATH}" || true
        fi
      shell: bash
