# action.yml

name: minio-upload
description: "Action that lets you upload objects from a MinIO server"
inputs:
  url:
    description: "URL of the MinIO server"
    required: true
  access-key:
    description: "Access Key for the MinIO server"
    required: true
  secret-key:
    description: "Secret Key for the MinIO server"
    required: true
  local-path:
    description: 'Path of the local object'
    required: true
    default: './'
  remote-path:
    description: 'Path to remote object'
    required: true
  policy:
    description: 'Policy'
    required: false

runs:
  using: composite
  steps:
    - name: Check if mc is installed
      id: check-mc
      run: |
        if [[ -n "$(which mc)" ]]; then
          echo "exists=true" >> "$GITHUB_OUTPUT"
        else
          echo "exists=false" >> "$GITHUB_OUTPUT"
        fi
      shell: bash

    - name: Download latest mc SHA256
      id: mc-sha
      if: ${{ steps.check-mc.outputs.exists == 'false' }}
      run: |
        sha=$(wget -qO- \
          https://dl.min.io/client/mc/release/linux-amd64/mc.sha256sum \
          | awk '{print $1}')
        echo "sha256=$sha" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Cache mc binary
      id: cache-mc
      if: ${{ steps.check-mc.outputs.exists == 'false' }}
      uses: actions/cache@v4
      with:
        path: /usr/local/bin/mc
        key: mc-${{ steps.mc-sha.outputs.sha256 }}

    - name: Setup mc
      working-directory: /usr/local/bin
      if: >-
        ${{ steps.check-mc.outputs.exists == 'false'
          && steps.cache-mc.outputs.cache-hit != 'true' }}
      run: |
        arch=$(dpkg --print-architecture | sed 's/armhf/arm/g')
        sudo wget --progres=dot:binary \
          "https://dl.min.io/client/mc/release/linux-${arch}/mc"
        sudo chmod +x mc
      shell: bash

    - name: Setup s3 alias
      run: |
        mc alias set s3 "${{ inputs.url }}" \
          "${{ inputs.access-key }}" "${{ inputs.secret-key }}"
      shell: bash

    - name: Upload objects
      run: |
        echo "Will upload ${{ inputs.local-path }} to ${{ inputs.remote-path }}"
        local_path=${{ inputs.local-path }}
        if [ "${local_path#*'*'}" != "$local_path" ]; then
          # Handle local_files with wildcards
          local_dir=$(dirname "$local_path")
          local_files=$(basename "$local_path")
          IFS=$'\n'
          for p in $(find "$local_dir" -maxdepth 1 -name "$local_files" | \
            sort -u); do
              [ "$p" = "$local_dir" ] && continue
              mc cp -r "$p" "s3/${{ inputs.remote-path }}"
          done
          unset IFS
        else
          mc cp -r "$local_path" "s3/${{ inputs.remote-path }}"
        fi
      shell: bash

    - name: Set policy
      run: |
        if [ "${{ inputs.policy }}" = 1 ] ; then
          echo "Will make ${{ inputs.remote-path }} public"
          mc anonymous -r set download "s3/${{ inputs.remote-path }}"
        else
          echo "Will make ${{ inputs.remote-path }} private"
          mc anonymous -r set private "s3/${{ inputs.remote-path }}" || true
        fi
      shell: bash
